### ISSUE TITLE
Getting errors on people export

### ISSUE THREAD

**Issue by zoltanf** [ak--47/mixpanel-import#7]
Used to work pretty reliably, but something changed recently.
Using the latest version (but same problem exists with a couple of versions back as well), getting error:
`ERROR: Cannot read properties of undefined (reading 'body')`

Randomly on different number of exported profiles;

in logs:
```
    {
      "message": "connect ETIMEDOUT 34.96.97.101:443"
    }
```

Would this mean we need to retry this somehow?

Thank you for the script AK :)

**Comment by ak--47** [comment]
@zoltanf are you passing any options other than `type` and auth params?

**Comment by ak--47** [comment]
if i had to guess, this is [rate limits](https://docs.mixpanel.com/docs/other-bits/rate-limits#:~:text=%3A%20A%20maximum%20of%205%20concurrent%20queries%20and%2060%20queries%20per%20hour.). are you able to reproduce consistently? 

i can't remember if i implemented a backoff for the export APIs, but i'll TAL...

out of curiosity, is this still for your project migration? why are you exporting profile data?

**Comment by zoltanf** [comment]
Sorry for the late answer, some holidays here.
Solved it temporarily by writing the export part in python, with some retry logic. 

Yes, still for our migration, we need to copy over the people profiles regularly from the US to EU props. 

Here is the command line used:
```
    result = subprocess.run(
        ['npx', f'--node-options="--max-old-space-size={heap_size}"', '--yes', f'mixpanel-import@{mi_npx_version}',
         '--type', 'peopleExport',
         '--project', f'{source_project}',
         '--acct', f'{source_acct}',
         '--pass', f'{source_pass}',
         '--where', f'ppl/'],
        capture_output=False, text=True
        )
```

Also, the import is problematic if there are more than 1000 files in the folder. I forgot to told you about this before, looks like the import tool tries to load all at once or something similar. Doing it in batches of 1000 works fine.

Thank you anyway, at this point for us it's fine like this, but you might run into the same problem in the future :)

Regards,
Z.

**Comment by ak--47** [comment]
this is actually a good catch, i do retries on [event exports](https://github.com/ak--47/mixpanel-import/blob/main/exporters.js#L22) ... but not on [people exports](https://github.com/ak--47/mixpanel-import/blob/main/exporters.js#L96) ... i will adjust in the next release

fwiw, this is my pure bash solve for the "export / import" use case:
https://gist.github.com/ak--47/05d73181bf85d4b47317dee9d16aed4d

(similar to what you're doing, just with pipes)

nice to hear from you!

**Comment by ak--47** [comment]
addressed in https://github.com/ak--47/mixpanel-import/commit/6234356244e29f6aa082bc307463b48a1c0764a0
